steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile.scorer",
        "-t",
        "us-east1-docker.pkg.dev/telco-churn-vinay-raw/cloud-run-source-deploy/telco-bq-scorer-service:latest",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/telco-churn-vinay-raw/cloud-run-source-deploy/telco-bq-scorer-service:latest"
      ]

images:
  - "us-east1-docker.pkg.dev/telco-churn-vinay-raw/cloud-run-source-deploy/telco-bq-scorer-service:latest"
